### PR TITLE
Implement support for Laravel 8

### PR DESCRIPTION
**Pull request by tenshiAMD**
Add support to use this package with Laravel 8.

### CODE REVIEW

**Comment by tenshiAMD** [comment]
Related to issue https://github.com/dwightwatson/validating/issues/223.

**Comment by dwightwatson** [comment]
Uh, you've bumped it to Laravel 9?

I added support for Laravel 8 in version `6.0.0`.

**Comment by tenshiAMD** [comment]
@dwightwatson your latest version is not working with latest version of Laravel 8 since its already \`v8.2.0\` as of the moment now

**Comment by dwightwatson** [comment]
`~8.0` allows it to be installed alongside any version that starts with 8.

I just successfully installed this package into a Laravel v8.2.0 project.

If you're having issues please provide some more information about what's happening on your end so we can get to the bottom of it.

**Comment by tenshiAMD** [comment]
@dwightwatson I see now the issue, I've used wrong package name `dwightwatson/validating` instead of `watson/validating` only, and misread the error. Thanks~! 🎉

**Pull request closed without merging**
