### PR TITLE
Infer unique additional where clause if not set

### PR DESCRIPTION
**Pull request by Omranic**

### CODE REVIEW

**Comment by dwightwatson** [comment]
Thanks for this - I'm happy for this to go in but would you be able to add some tests so we can be sure it works the way it's expected to?

**Comment by Omranic** [comment]
@dwightwatson Done 👍

**Comment by dwightwatson** [comment]
Champion - thank you!

**Comment by Omranic** [comment]
Awesome, thanks for the great package by the way 🙂

**Pull request merged**
