### PR TITLE
Remove array_filter as it strips off int 0 values

### PR DESCRIPTION
**Pull request by CyrilMazur**
Fixes https://github.com/dwightwatson/validating/issues/137

### CODE REVIEW

**Comment by dalabarge** [comment]
Might want to consider a custom array_filter callback to deal with nulls and empty string values instead of just removing the array_filter.

**Comment by dwightwatson** [comment]
Hey, thanks for taking the time to put together this PR!

I agree that a custom `array_filter` might be a better course of action here. Because `explode()` returns an array of strings I don't think it would be possible to have a `null` value. Perhaps the only value that should be stripped then is an empty string. 

    $parameters = array_filter(explode(',', substr($rule, 7)), function ($value) 
    {
        return $value !== '';
    });

**Comment by CyrilMazur** [comment]
Is this still useful? I mean, in what situation can we have an empty string there? Is it just in case the developer is making a typo in the format like:

```php
"unique:accounts,email,NULL,id,deleted,0," // with an extra coma at the end
```

?

**Comment by dwightwatson** [comment]
Hm, it looks as though the `array_filter` was introduced in #111 and #112 (for both the `0.10` and `master` branches), but the user has since deleted their account. I see what you're saying about #107,

It used to pop the table and field name in for you if they weren't supplied, but since it now looks for a rule called `unique:` with the colon at the end (see [L405-408](https://github.com/dwightwatson/validating/blob/master/src/ValidatingTrait.php#L405-L408)) this no longer works as expected.

I'll merge this PR and I'll also remove the dead code for inserting table and field names. Thanks again!

**Comment by CyrilMazur** [comment]
My pleasure, great piece of software.

**Pull request merged**
