### PR TITLE
Provide support for custom unique-like rules

### PR DESCRIPTION
**Pull request by Propaganistas**
New PR for the case described in #153 and #154 .
I couldn't let this go :-)

I think this is a clean implementation of the way you described.
I added support for `unique_with` but of course this can be removed if you feel this shouldn't be in core.

--> `$uniqueIdentifierInjectors` can be overridden in a model to map the corresponding injection method.
--> by defining those methods in a model, both the built-in unique injectors as well as new injectors can be (re)defined on a per-model basis.

I'll leave the readme entry to you.

### CODE REVIEW

**Comment by dwightwatson** [comment]
Thanks for persevering and taking the time for this PR. I haven't been trying to make things hard for you, just wanted to make sure we were heading int he right direction.

I'll tweak this a little bit, write some additional tests and then play with it before tagging a new release.

**Comment by dwightwatson** [comment]
Also, are you able to clarify what the regular expression in the `unique_with` rule is trying to do?

**Comment by Propaganistas** [comment]
No problem, thanks for considering this!

Concerning the regex: `unique_with` implements the current row id as the last parameter (always), but allows another column to be designated as the id (format: `ID = custom_column_id`, e.g. `unique_with:table,column,1=relation_id`). The regex checks for existence of the last parameter as either a single integer or an id combined with a designated column (with or without whitespaces). I hope it's clear like this?

**Comment by dwightwatson** [comment]
Ah gotcha, I missed the `id = custom_column` syntax from the `unique_with` docs. Just wanted to confirm as I didn't want to break anything. Thanks for clarifying.

I've adjusted the code a little so that it doesn't need the accessor and instead just infers whether an injector is supported based on a dynamic method name. A little easier and sort-of goes with the dynamic methods that Eloquent provides anyway.

**Pull request merged**
